spring.profiles.active: local

spring:
  config:
    import:
      - eureka.yml
      - mysql.yml
      - redis.yml
      - swagger.yml
      - crypto.yml
  application:
    name: stock-service

server:
  port: ${APPLICATION_PORT:8083}
  tomcat:
    max-connections: 10000
    threads:
      max: 200
      min-spare: 20

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod

