spring:
  elasticsearch:
    host: localhost
    port: 9200

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

spring:
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}

---
spring.config.activate.on-profile: prod

spring:
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}